name: virtualFit
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip=21.1.3
  - python=3.8.12
  - pip:
    - playsound==1.3.0
    - notebook==6.4.0
    - mediapipe==0.8.9.1
    - pandas==1.3.0
    - opencv-python==4.3.0.36
    - streamlit==1.3.1
    - gTTS==2.2.3
    - joblib==1.0.1
    - xgboost==1.5.2
    - scikit-learn==0.24.2
